blueprints/auth.py
# blueprints/auth.py
from flask_login import LoginManager, login_required, login_user, logout_user, current_user
from flask import Blueprint, render_template, redirect, url_for, request, flash, abort
from model.model import User,Role
from model.connection import db
from functools import wraps

login_manager = LoginManager()
login_manager.login_view = 'auth.login'

app = Blueprint('auth', __name__)

# decoratore fornito dal docente tramite moodle, gestisce i permessi di accesso alle pagine in bas al ruolo
def user_has_role(*role_names):
    def decorator(f):
        @wraps(f)
        def decorated_function(*args, **kwargs):
            if not current_user.is_authenticated:
                flash("Devi essere autenticato per accedere a questa pagina.")
                return redirect(url_for('login'))
            if not any(current_user.has_role(role) for role in role_names):
                flash("Non hai il permesso per accedere a questa pagina.")
                return abort(403)
            return f(*args, **kwargs)
        return decorated_function
    return decorator

# route per il login, ritorna la pagina di login
@app.route('/login')
def login():
    return render_template('auth/login.html')

# route una volta eseguito il login, gestisce i dati ottenuti e autentica l'utente
@app.route('/login', methods=['POST'])
def login_post():
    # manages the login form post request
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(email=email).first()

    if not user or not user.check_password(password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login'))

    login_user(user, remember=remember)

    if user.has_role("admin"):
        return redirect(url_for('admin.get_richieste'))
    elif user.has_role("user"):
        return redirect(url_for('user.get_lista_vm'))
    else:
        flash("Account senza ruolo: contatta un admin.")
        logout_user()
        return redirect(url_for('auth.login'))
 

# route per eseguire il logout dell'utente autenticato
@app.route('/logout')
@login_required
@user_has_role("admin", "user")
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

# route per la registrazione, ritorna la pagina di registrazione
@app.route('/signup')
def signup():
    return render_template('auth/signup.html')

# route una volta eseguita la registrazione, gestisce i dati ottenuti e crea l'utente
@app.route('/signup', methods=['POST'])
def signup_post():
    username = request.form["username"]
    email = request.form["email"]
    password = request.form["password"]


    user = User.query.filter_by(email=email).first()
    if user:
        flash('User with this email address already exists')
        return redirect(url_for('auth.signup'))

    user = User(username=username, email=email)
    user.set_password(password)

    user_role = Role.query.filter_by(name='user').first()
    if user_role:
        user.roles.append(user_role)

    db.session.add(user)
    db.session.commit()

    return redirect(url_for('auth.login'))


@login_manager.user_loader
def load_user(user_id):
    stmt = db.select(User).filter_by(id=user_id)
    user = db.session.execute(stmt).scalar_one_or_none()    
    return user

blueprints/user.py
# blueprints/user.py
from flask_login import LoginManager, login_required, current_user
from flask import Blueprint, render_template, redirect, url_for, request, flash
from model.model import User, VmRequest, VmCredentials
from model.connection import db
from blueprints.auth import user_has_role

app = Blueprint('user', __name__)

# route per visualizzare il form di richiesta creazione VM
@app.route('/creazione_vm')
@login_required
@user_has_role("user")
def get_creazione_form():
    return render_template('user/creazione.html')

# route per visualizzare la lista delle VM dell'utente, fornisce tutte le credenziali d'accesso salvate in DB
@app.route('/lista')
@login_required
@user_has_role("user")
def get_lista_vm():
    credenziali = (VmCredentials.query.join(VmRequest, VmCredentials.vm_request_id == VmRequest.id).filter(VmRequest.user_id == current_user.id).
                   order_by(VmCredentials.add_ts.desc()).all())
    
    return render_template('user/lista_vm.html', credentials=credenziali)

# route per gestire la richiesta di creazione VM
# controlla il tipo della VM e salva nel DB la richiesta con stato PENDING
@app.route('/creazione_vm', methods=['POST'])
@login_required
@user_has_role("user")
def crea_vm():

    vm_type_id = int(request.form.get('vm_type_id'))
    if vm_type_id is None:
        return redirect(url_for('user.get_creazione_form'))

    new_request = VmRequest(vm_type_id=vm_type_id, user_id=current_user.id, status='PENDING')
    db.session.add(new_request)
    db.session.commit()
    flash("Richiesta di creazione VM inviata")
    return redirect(url_for('user.get_creazione_form'))

templates/user/creazione.html
<!-- user/creazione.html -->
{% extends "base.html" %}
{% block content %}
<div class="login-root">
  <div class="formbg">
    <div class="formbg-inner">
      <span class="title">Richiedi una nuova VM:</span>

      <form class="vm-form" method="POST" action="{{ url_for('user.crea_vm') }}">
        <div class="field">
          <label for="vm_type_id">Tipo di VM:</label>
          <select class="select" id="vm_type_id" name="vm_type_id" required>
            <option value="0">Bronze</option>
            <option value="1">Silver</option>
            <option value="2">Gold</option>
          </select>
        </div>

        <button class="btn-submit" type="submit">Richiedi VM</button>
      </form>
      {% with messages = get_flashed_messages() %}
            {% if messages %}
              <div class="alert alert-danger" role="alert">
                {% for message in messages %}
                  <p style="color: green;">{{ message }}</p>
                {% endfor %}
              </div>
            {% endif %}
        {% endwith %}
    </div>
  </div>
</div>

<div class="info-card">
    <div class="info-card__header">
      <h2 class="info-card__title">Informazioni relative ai 3 tipi di macchina:</h2>
    </div>

    <div class="info-card__body">
      <div class="info-card__tips">
        <div class="tip">
          <span class="tip__title">Bronze:</span>
          <ul>
            <li><span class="tip__text">1 core</span></li>
            <li><span class="tip__text">512mb RAM</span></li>
            <li><span class="tip__text">10GB disk</span></li>
          </ul>
        </div>

        <div class="tip">
          <span class="tip__title">Silver:</span>
          <ul>
            <li><span class="tip__text">2 core</span></li>
            <li><span class="tip__text">1024mb RAM</span></li>
            <li><span class="tip__text">15GB disk</span></li>
          </ul>
        </div>

        <div class="tip">
          <span class="tip__title">Gold:</span>
          <ul>
            <li><span class="tip__text">4 core</span></li>
            <li><span class="tip__text">2048mb RAM</span></li>
            <li><span class="tip__text">20GB disk</span></li>
          </ul>
        </div>
      </div>
    </div>
</div>
{% endblock %}

templates/user/header.html
<!--user/header.html-->
<div class="header">
  <a href="{{ url_for('user.get_lista_vm') }}" class="logo">ProxMox Portal</a>
  <div class="header-right">

    <a href="{{ url_for('user.get_lista_vm') }}"
       class="{{ 'active' if request.endpoint == 'user.get_lista_vm' else '' }}">
      Lista VM
    </a>

    <a href="{{ url_for('user.get_creazione_form') }}"
       class="{{ 'active' if request.endpoint == 'user.get_creazione_form' else '' }}">
      Richiedi VM
    </a>

    <a href="{{ url_for('auth.logout') }}">Logout</a>
  </div>
</div>

templates/user/lista_vm.html
<!-- user/lista_vm.html -->
{% extends "base.html" %}
{% block content %}
    <h1 class="table-title">Lista delle tue VM</h1>
    <div class="table-container">
    <table class="styled-table">
        <thead>
        <tr>
            <th>Hostname</th>
            <th>Indirizzo IP</th>
            <th>Username</th>
            <th>Password</th>
            <th>Data Creazione</th>
        </tr>
        </thead>
        <tbody>
            {% for c in credentials %}
            <tr>
                <td>{{ c.hostname }}</td>
                <td>{{ c.ip_address }}</td>
                <td>{{ c.username }}</td>
                <td>{{ c.password }}</td>
                <td>{{ c.add_ts }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div><br><br>


    <div class="info-card">
    <div class="info-card__header">
      <h2 class="info-card__title">Istruzioni per accedere alla propria macchina virtuale:</h2>
      <p class="info-card__subtitle">
        Utilizza le informazioni riportate nella tabella per accedere.
      </p>
    </div>

    <div class="info-card__body">
      <div class="info-card__tips">
        <div class="tip">
          <span class="tip__title">Istruzioni d'accesso alla macchina da terminale CMD:</span>
          <ul>
            <li><span class="tip__text">ssh [username]@[indirizzo ip]</span></li>
            <li><span class="tip__text">in seguito inserisci la password mostrata nella tabella</span></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

{% endblock %}